add script for running on staged files

diff --git a/mesaic-codeformat b/mesaic-codeformat
--- a/mesaic-codeformat
+++ b/mesaic-codeformat
@@ -1,3 +1,11 @@
 #!/usr/bin/env sh
+if [ ! -f node_modules/.bin/prettier ]; then
+  echo "node_modules/.bin/prettier not found."
+  exit 1
+fi
+if [ ! -f node_modules/.bin/eslint_d ]; then
+  echo "node_modules/.bin/eslint_d not found."
+  exit 1
+fi
 node_modules/.bin/prettier --write --print-width 100 --single-quote --trailing-comma es5 --no-bracket-spacing --jsx-bracket-same-line "$@"
 node_modules/.bin/eslint_d --no-eslintrc -c ./node_modules/eslint-config-mesaic/fix.js --fix "$@"
