use diff to detect eslint/prettier errors

diff --git a/mesaic-codeformat-check b/mesaic-codeformat-check
--- a/mesaic-codeformat-check
+++ b/mesaic-codeformat-check
@@ -7,31 +7,26 @@ jsfiles="$@"
 
 echo >&2 $RED
 
-prettier_diffs=$(node_modules/.bin/prettier -l --arrow-parens always --print-width 100 --single-quote --trailing-comma all --no-bracket-spacing --jsx-bracket-same-line $jsfiles)
-
-test_eslint() {
+test_files() {
   for f in $jsfiles; do
-    ./node_modules/.bin/eslint_d --stdin --stdin-filename $f --no-eslintrc -c  ./node_modules/@mesaic/eslint-config-mesaic/fix.js < $f 2>&1 >/dev/null
+    cat $f | \
+    ./node_modules/.bin/prettier --arrow-parens always --print-width 100 --single-quote --trailing-comma all --no-bracket-spacing --jsx-bracket-same-line --stdin |\
+    ./node_modules/.bin/eslint_d --stdin --fix-to-stdout --no-eslintrc -c ./node_modules/@mesaic/eslint-config-mesaic/fix.js 2> /dev/null | \
+    diff $f - &>/dev/null
     if [ "$?" != "0" ]; then
       echo $f
     fi
   done
 }
 
-eslint_diffs=$(test_eslint)
+diffs=$(test_files)
 
 exit_code=0
 
-if [ ! -z "$prettier_diffs" ]; then
+if [ ! -z "$diffs" ]; then
   exit_code=1
-  echo >&2 "${RED}Javascript files must be formatted with prettier. Please run \`npm run format-staged\`. Failed files:"
-  for file in $prettier_diffs; do echo >&2 "- $file"; done
-fi
-
-if [ ! -z "$eslint_diffs" ]; then
-  exit_code=1
-  echo >&2 "${RED}Javascript files must be valid with eslint. Please run \`npm run format-staged\`. Failed files:"
-  for file in $eslint_diffs; do echo >&2 "- $file"; done
+  echo >&2 "${RED}Javascript files must be valid with eslint and prettier. Please run \`npm run format-staged\`. Failed files:"
+  for file in $diffs; do echo >&2 "- $file"; done
 fi
 
 echo >&2 "${NC}"
